### ISSUE TITLE
public chat don't work

### ISSUE THREAD

**Issue by NAGNOUMAD** [mynaparrot/plugNmeet-WordPress#10]
Hello all, first thank's for this great  plugin . I am using it but public chat on live don't work.
thanks for your response

**Comment by jibon57** [comment]
This may happen because of internet connection. Websocket connection dropped. You can try to reload the page. Make sure that the server you've installed `plugnmeet-server` has good connectivity.

**Comment by NAGNOUMAD** [comment]
I am using wordpress plugin

**Comment by NAGNOUMAD** [comment]
and I have try many time  to reload it it's seem not work. Thanks

**Comment by jibon57** [comment]
OK, you are using demo server. You can setup your own server by following: https://www.plugnmeet.org/docs/installation
Or can take cloud service: https://www.plugnmeet.cloud

**Comment by NAGNOUMAD** [comment]
on the demo chat it'snot working like my wordpress. Thanks
