### ISSUE TITLE
The meeting login form on WordPress 

### ISSUE THREAD

**Issue by wbobteng** [mynaparrot/plugNmeet-WordPress#4]
![loginform](https://user-images.githubusercontent.com/34347796/167025176-f10f5921-af7a-4cc5-9675-3fca56d36d83.png)
For this standard login form, I would suggest removing this highlighted part. 
It will be easier for the end-user to design and make it fit with the WordPress page. 
Just a simple login form and users can add whatever instructions they want from WordPress. Also, they can insert this form into any sections they want.

**Comment by jibon57** [comment]
solved: https://github.com/mynaparrot/plugNmeet-WordPress/commit/8ed32f420941eb789d80c0191ec6897dba687785
